theme: jekyll-theme-leap-day
title: Pedometer
show_downloads: true
titles_from_headings:
  enabled: false
author:
  name: "Java+Android Student"
  href: "https://ddc-java-10.github.io/android-pedometer/"
  
